tests

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -21,6 +21,31 @@ jobs:
     steps:
       - checkout
 
+      - setup_remote_docker
+      - run: |
+          echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
+          docker run -idt --rm -v /sys/fs/cgroup:/sys/fs/cgroup:ro -p 80:80 --tmpfs /run --tmpfs /run/lock --name=mamlambo lhotakj/centos-apache-mod_wsgi-python3:3.7.4
+
+          HTTP_STATUS="$(curl -IL --silent http://localhost:80 | grep HTTP )"
+          SERVER_HEADER=$(curl -IL --silent http://localhost:80 | grep Server:)"
+
+          if [[ ! $HTTP_STATUS =~ "200 OK" ]]
+          then
+             echo "Invalid HTTP code: $HTTP_STATUS"
+             docker container kill mamlambo
+             exit 1
+          fi
+
+          if [[ ! $SERVER_HEADER =~ "mod_wsgi/4.6.5" ]]
+          then
+             echo "Invalid Server header: $SERVER_HEADER"
+             docker container kill mamlambo
+             exit 1
+          fi
+
+          echo "killing container"
+          docker container kill mamlambo
+
       # Download missing tools
       - run:
           name: install additional packages
